### ISSUE TITLE
Press of an Enter key should send the message

### ISSUE THREAD

**Issue by Kieshas** [Kieshas/ElectroTerm#8]

**Comment by Kieshas** [comment]
Also, program should not send anything if input field is empty

**Comment by erstec** [comment]
@Kieshas it can send just CR/LF, why not?  )

**Comment by Kieshas** [comment]
@erstec Do not really see a use case for such feature. It doesn't hurt but IMO it would be nicer

**Comment by erstec** [comment]
It is very common if you decide to communicate for ex with modem wich have autobaud enabled, as it need to send several CRLF's in a row to let autobaud work (there is more devices acting like that), but it is up to you to decice

**Comment by Kieshas** [comment]
In that case it is mandatory to leave it as is I think.
